# Question wordings and translations
```{r wording_setup, include=FALSE, echo=FALSE}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
knitr::opts_chunk$set(echo = TRUE, knitr.kable.NA = "", cache = FALSE, message = FALSE )
```
Below are the question wordings of the text that is not retrievable in the data set. Languages are English (translated), Icelandic, Norwegian, and Swedish.
The variable placements in the text are indicated in [BRACKETS].

## NORDFORSK1

>Could you please now imagine that an incident has taken place in the Nordic region and then consider some questions about the incident below.
The incident involves a [NORDFORSK1_TACTIC1] that targeted [NORDFORSK1_TARGET] [in/on country]. 
[NORDFORSK1_CASUALTIES] were killed in [NORDFORSK1_TACTIC2], which was performed by [NORDFORSK1_ADJECTIVE] [NORDFORSK1_SUBJECTIVE]. 
News coverage suggests [NORDFORSK1_MOTIVATION].


Icelandic  
[NORDFORSK1_TACTIC1] sér stað við [NORDFORSK1_TARGET] á Íslandi. [NORDFORSK1_CASUALTIES] í [NORDFORSK1_TACTIC2] sem [tid(singular/plural)] framkvæmd af [NORDFORSK1_ADJECTIVE] [NORDFORSK1_SUBJECTIVE]. Fréttaumfjöllun bendir til að [NORDFORSK1_MOTIVATION]. Myndir þú flokka þetta sem hryðjuverk? 

Norwegian  
Vi ber deg nå se for deg en tenkt hendelse i Norden, og ta stilling til noen spørsmål vi stiller om hendelsen under.
Hendelsen gjelder en  [NORDFORSK1_TACTIC1] som fant sted [NORDFORSK1_TARGET] i Norge. 
[NORDFORSK1_CASUALTIES] ble drept i [NORDFORSK1_TACTIC2], som ble utført av [NORDFORSK1_ADJECTIVE] [NORDFORSK1_SUBJECTIVE].
Nyhetsdekningen tyder på [NORDFORSK1_MOTIVATION].

Swedish  
Vi ber dig nu att föreställa dig en påhittad händelse i Norden och svara på några frågor om
händelsen. 
[NORDFORSK1_TACTIC1] inträffade [NORDFORSK1_TARGET] i Sverige. [NORDFORSK1_CASUALTIES]
dödades i [NORDFORSK1_TACTIC2] som utfördes av [NORDFORSK1_ADJECTIVE]
[NORDFORSK1_SUBJECTIVE]. Nyhetsrapporteringen tyder på [NORDFORSK1_MOTIVATION].

### NORDFORSK1_DV_A

> Would you classify this incident as an act of terrorism?


Icelandic  
Myndir þú flokka þetta sem hryðjuverk?

Norwegian  
Vil du klassifisere denne hendelsen som terrorisme?

Swedish  
Skulle du säga att detta är terrorism?

### NORDFORSK1_DV_B

> Imagine that the authorities suspected that this incident was imminent. 
To what extent do you agree or disagree that the authorities should have the right to:


Icelandic  
Ímyndum okkur að yfirvöld hefðu grun um að þetta atvik væri yfirvofandi. 
Hversu sammála eða ósammála ert þú því að yfirvöld ættu að hafa réttinn til að gera eftirfarandi?

Norwegian  
Tenk deg at myndighetene hadde mistanke om at denne hendelsen var nært forestående. Hvor enig eller uenig er du i at myndighetene burde har rett til å:

Swedish  
Föreställ dig att myndigheterna misstänkte att denna händelse var nära förestående. Hur
för eller emot är du att myndigheterna borde ha rätt till att:


### NORDFORSK1_DV_B_1

> Hold people in custody as long as they want without charging them


Icelandic  
Halda fólki í gæsluvarðhaldi eins lengi og þau vilja án ákæru.

Norwegian  
Holde personer i forvaring så lenge de vil uten å stille dem for retten.

Swedish  
Hålla personer häktade utan att ställa inför rätta.

### NORDFORSK1_DV_B_2

> Listen in on people's telephone conversations


Icelandic  
Hlera símtöl fólks

Norwegian  
Avlytte folks telefonsamtaler

Swedish  
Avlyssna människors telefonsamtal


### NORDFORSK1_DV_B_3

> Randomly stop and search people on the street


Icelandic  
Stöðva fólk af handahófi úti á götu og leita á því

Norwegian  
Tilfeldig stoppe og ransake folk på gaten

Swedish  
Tillfälligt stoppa och visitera människor på gatan


### NORDFORSK1_DV_B_4

> Conduct surveillance of people's Email and Internet communications


Icelandic  
Fylgjast með tölvupósti fólks og öðrum upplýsingum sem sendar eru á netinu

Norwegian  
Overvåke folks epost og internettkommunikasjon

Swedish  
Övervaka människors epost och internetkommunikation

### NORDFORSK1_DV_B_5

> Conduct surveillance/wire tapping of rooms


Icelandic  
Vakta/hlera húsnæði fólks

Norwegian  
Overvåke/avlytte rom

Swedish  
Övervaka/avlyssna rum

### NORDFORSK1_DV_B_6

> Cordon off parts of the city

Icelandic  
Loka af hluta borgarinnar/bæjarins

Norwegian  
Sperre av deler av byrommet

Swedish  
Spärra av delar av staden/orten

### NORDFORSK1_DV_B_7

> Let armed police or the army patrol the streets

Icelandic  
Láta vopnaða lögreglu eða her vakta göturnar

Norwegian  
La bevæpnet politi eller forsvaret patruljere gatene

Swedish  
Låta beväpnad polis eller försvaret patrullera gatorn


## NORDFORSK2
> Overall, how serious a threat do you perceive terrorism to be for [NORDFORSK2_OBJECT] [NORDFORSK_TENSE]?


Icelandic  
Þegar á heildina er litið, hversu alvarlega ógn telur þú hryðjuverk vera fyrir [NORDFORSK2_OBJECT] [NORDFORSK_TENSE]?

Norwegian  
Hvor stor trussel er terror for [NORDFORSK2_OBJECT] [NORDFORSK_TENSE].

Swedish  
I allmänhet, hur allvarligt hot uppfattar du att terrorism är för x? ">I allmänhet, hur allvarligt hot uppfattar du att terrorism är för [NORDFORSK2_OBJECT] [NORDFORSK_TENSE]?

## NORDFORSK3
> To what extent do you agree that the safeguarding of society's security should be at the expense of individuals' freedom (such
as protection of privacy and the right to privacy)?


Icelandic  
Hversu sammála ert þú að verndun öryggis í samfélaginu ætti að vera á kostnað einstaklingsfrelsis (til dæmis persónuverndar og réttinum til einkalífs)?

Norwegian  
Ivaretakelse av sikkerhet bør gå på bekostning av enkeltindividers frihet.

Swedish  
I vilken utsträckning samhällets säkerhet på bekostnad av individers frihet?

## NORDFORSK4
> How important are anti-terrorism measures for you personally?


Icelandic  
Hversu mikilvægar finnst þér aðgerðir gegn hryðjuverkum vera?

Norwegian  
Hvor viktig er antiterrortiltak for deg.

Swedish 
Hur viktiga är åtgärder mot terrorism för dig personligen?

## NORDFORSK5

> Which political party do you think has the best policies aimed at combating terrorist attacks in [Iceland / Norway / Sweden]?


Icelandic  
Hvaða stjórnmálaflokkur telur þú að hafi bestu stefnu til að sporna við hryðjuverkum á Íslandi?

Norwegian  
Hvilket parti har den beste antiterrorpolitikken.

Swedish  
Bästa part för bekämpa terrorism?

## NORDFORSK6
> In your opinion, how good or bad are the following actors [on Iceland / in Norway / in Sweden] regarding their ability to deal with the risk of terrorist attacks?


Icelandic  
Hversu vel eða illa telur þú að eftirfarandi aðilar á Íslandi séu í stakk búnir til að bregðast við hættunni sem stafar af hryðjuverkaárásum? 

Norwegian  
Hvor godt eller dårlig vil du si at følgende aktører i Norge er i stand til å håndtere faren for terrorangrep? 

Swedish 
Hur bra eller dåliga skulle du säga att följande aktörer i Sverige är på att hantera risken för
terrorattacker?

## NORDFORSK6_1

> International organizations

Icelandic  
Alþjóðastofnanir

Norwegian  
Internasjonale organisasjoner

Swedish  
Internationella organisationer


## NORDFORSK6_2

> National authorities

Icelandic  
Ríkisstjórnin

Norwegian  
Nasjonale myndigheter

Swedish  
Nationella myndigheter

## NORDFORSK6_3

> Local authorities

Icelandic  
Sveitarstjórnir

Norwegian  
Lokale myndigheter

Swedish  
Lokala myndigheter

## NORDFORSK6_4

> The police

Icelandic  
Lögreglan

Norwegian  
Politiet

Swedish  
Polisen   

## NORDFORSK6_5

> NGOs

Icelandic  
Frjáls félagasamtök

Norwegian  
Frivillige organisasjoner

Swedish  
Frivilligorganisationer


## NORDFORSK6_6

> Individual citizens

Icelandic  
Almennir borgarar

Norwegian  
Den enkelte innbygger

Swedish  
Den enskilde invånaren


> Presently, there is great deal of attention focused on [NORDFORSK7_EVENT]. 
The state can put various measures in place to reduce the risk of [NORDFORSK7_EVENT], but there is controversy over how much money the state should prioritize to spend on such measures.


Icelandic  
Þessa dagana er mikið rætt um [Field-terror10_a]. Ríkisstjórnin getur gripið til ýmissa aðgerða til að draga úr hættunni á [Field-terror10_b], en fólk er ósammála um hversu miklum peningum ríkið eigi að nota til að leggja áherslu á slík úrræði. 

Norwegian  
I disse dager er det stor oppmerksomhet rundt [NORDFORSK7_EVENT]. 
Staten kan sette inn ulike tiltak for å redusere faren for [NORDFORSK7_EVENT], men det er uenighet om hvor mye penger staten bør prioritere å bruke på slike tiltak.

Swedish  
För närvarande är det mycket uppmärksamhet kring [NORDFORSK7_EVENT]. Staten kan
vidta olika åtgärder för att minska risken för [NORDFORSK7_EVENT], men det råder oenighet om hur mycket pengar staten bör prioritera att spendera på sådana åtgärder.
 

## NORDFORSK7

### NORDFORSK7_DV
> If the state can expect to save one human life by spending NOK 100 million on measures to reduce the risk of [NORDFORSK7_EVENT], do you think the state should prioritize these measures? These measures should be carried out if they have to be funded through increased taxes among the population?


Icelandic
Ef ríkið getur reiknað með að bjarga einu mannslífi með því að eyða 1.500 milljónum króna í úrræði til að draga úr líkunum á dauðsföllum vegna [Field-terror10_c], ert þú hlynnt(ur) því að ríkið eigi að setja þessi úrræði í forgang? Ætti ríkisstjórnin að ráðast í slíkar ráðstafanir ef það verður að fjármagna þær með hærri sköttum á almenning?

Norwegian  
Hvis staten kan regne med å redde ett menneskeliv ved å bruke 100 millioner kroner på tiltak for å redusere faren
[NORDFORSK7_EVENT], synes du staten bør prioritere disse tiltakene?

Swedish  
Om staten kan räkna med att rädda ett människoliv genom att spendera 100 miljoner kronor på åtgärder för att minska risken för [NORDFORSK7_EVENT], tycker du att staten borde prioritera dessa åtgärder?

## NORDFORSK8

> Over the past twenty years, there have been high levels of immigration from Muslim countries in Africa, Asia and the Middle
East to Europe.
There are differences in how strict certain countries are regarding their immigration policies. There are also differences
regarding which countries Muslims typically prefer to emigrate to. By gathering large amounts of data, researchers can use
these differences to study the correlation between Muslim immigration and terrorism.
A US research team recently used data from 174 countries during the period of 1995-2015 to study how the probability of
terrorism changed as a result of increased immigration from Muslim countries.


Icelandic  
Til upplýsingar, rannsakendurnir sem greindu tengslin milli innflytjenda frá löndum þar sem múslimar eru í meirihluta og hryðjuverkaárása í móttökulöndum komust að því að aukinn fjöldi innflytjenda frá múslimskum löndum hefði engin áhrif á fjölda hryðjuverka í móttökulöndunum.Telur þú að 

Norwegian  
I løpet av de siste tjue årene har det vært høy innvandring fra muslimske land i Afrika, Asia og Midtøsten til Europa.
Det er variasjon i hvor streng innvandringspolitikk som praktiseres mellom land. Det er også variasjon med tanke på hvilke
land muslimer typisk foretrekker å emigrere til. Ved å samle store mengder data kan forskere bruke denne variasjonen til å
studere sammenhengen mellom muslimsk innvandring og terrorisme.
Et forskerteam fra USA brukte nylig data fra 174 land i perioden 1995-2015 til å studere hvordan sannsynligheten for
terrorisme endret seg som følge av økt innvandring fra muslimske land.

Swedish  
Under de senaste tjugo åren har det varit hög invandring från muslimska länder i Afrika,
Asien och Mellanöstern till Europa.
Det finns skillnader i hur strikt invandringspolitik olika länder har.
Det finns också skillnader gällande vilka länder muslimer vanligtvis föredrar att emigrera till.
Genom att samla in stora mängder data kan forskare använda dessa skillnader till att studera förhållandet mellan muslimsk invandring och terrorism.
Ett amerikanskt forskarteam använde nyligen data från 174 länder under perioden 1995-2015 för att studera hur sannolikheten för terrorism förändrades till följd av ökad invandring från muslimska länder.


## NORDFORSK8_PRE

>  During the period of 1995-2015, how do you think increased immigration from Muslim-majority countries influenced
recipient countries?


Icelandic
Hvaða áhrif telur þú að aukinn fjöldi innflytjenda frá löndum þar sem múslimar eru í meirihluta hafi haft á móttökulöndin á árunum 1995 til 2015?

Norwegian  
I løpet av perioden 1995-2015, hvordan tror du økt innvandring fra muslimske majoritetsland påvirket mottakerlandene?

Swedish  
Under perioden 1995-2015, hur tror du att ökad invandring från muslimska majoritetsländer har
påverkat mottagarländerna?


## NORDFORSK8_DV_A
 > Over the next ten years, do you think the terror threat in [country] will increase if we choose to receive more immigrants from Muslim countries in Africa, Asia, and the Middle East? The terror threat will...


Icelandic  

Telur þú að hryðjuverkaógnin á Íslandi muni aukast á næstu tíu árum ef við tökum á móti fleiri innflytjendum frá múslimskum löndum í Afríku, Asíu og Miðausturlöndum?

Norwegian  
I løpet av de neste ti årene, tror du terrorfaren i Norge vil øke hvis vi velger å ta imot flere innvandrere fra muslimske land i Afrika, Asia og Midtøsten? Terrorfaren vil...

Swedish  
Inom de kommande tio åren, tror du att risken för terrorattacker i Sverige kommer att öka om vi väljer att ta emot fler invandrare från muslimska länder i Afrika, Asien och Mellanöstern? Risken för terrorattacker kommer att…


### NORDFORSK8_DV_B

>There is an ongoing debate in Norwegian about how many refugees we should receive. 
Do you think Norway should receive more or fewer refugees than it does today?

Icelandic  
Nú stendur yfir umræða á Íslandi um hversu mörgum flóttamönnum við eigum að taka á móti. Telur þú að Ísland eigi að taka á móti fleiri eða færri flóttamönnum en gert er í dag?

Norwegian  
Det er en pågående debatt i Norge om hvor mange flyktninger vi bør ta imot. Synes du Norge bør ta imot flere eller færre flyktninger enn i dag?

Swedish  
Tycker du att Sverige bör ta emot fler eller färre flyktingar än idag? 

### NORDFORSK8_DV_C

> To what extent do you agree or disagree that Norway should reduce the proportion of refugees with Muslim backgrounds?

Icelandic  

Hversu sammála eða ósammála ert þú að Ísland eigi að reyna að lækka hlutfall flóttamanna sem eru múslimar?

Norwegian  
Noen mener Norge bør redusere andelen muslimske flyktninger vi tar imot.
Hvor enig eller uenig er du i at Norge bør redusere andelen flyktninger med muslimsk bakgrunn?

Swedish  
Hur för eller emot Sverige  minska andelen flyktingar med muslimsk bakgrund?

