# POOL DATASETS

```{r POOL_setup, include=FALSE, echo=FALSE}
if(!require("gt")){install.packages("gt");  library(gt)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
if(!require("labelled")){install.packages("labelled");  library(labelled) }
if(!require("magick")){install.packages("magick");  library(magick)}
if(!require("openxlsx")){install.packages("openxlsx");  library(openxlsx)}
if(!require("readxl")){install.packages("readxl");  library(readxl)}
if(!require("sjlabelled")){install.packages("sjlabelled");  library(sjlabelled)}
if(!require("sjPlot")){install.packages("sjPlot");  library(sjPlot)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}
if(!require("utf8")){install.packages("utf8");  library(utf8)}
if(!require("webshot")){install.packages("webshot");  library(webshot)}
if(!require("surveytoolbox")){devtools::install_github("martinctc/surveytoolbox");  library(surveytoolbox)}

knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = "", cache = FALSE, message = FALSE )
```

```{r pool_load_iceland}
#Iceland
##Load data
di <- read_sav('C:\\Users/svein/Documents/NORDFORSKdata/Terrorism_Iceland_EnglishLabelss.sav')

## Select variables and rename to harmonized variable names
di_pool <- di %>% select(ResponseId = ResponseId,
NORDFORSK1_TACTIC1 = taktikk1,
NORDFORSK1_TARGET = mal,
NORDFORSK1_CASUALTIES = personer,
NORDFORSK1_TACTIC2 = taktikk2,
NORDFORSK1_ADJECTIVE = adjektiv,
NORDFORSK1_SUBJECTIVE = subjekt,
NORDFORSK1_MOTIVATION = motivasjon,
NORDFORSK1_DV_A = sp3,
NORDFORSK1_DV_B_1 = sp4_1,
NORDFORSK1_DV_B_2 = sp4_2,
NORDFORSK1_DV_B_3 = sp4_3,
NORDFORSK1_DV_B_4 = sp4_4,
NORDFORSK1_DV_B_5 = sp4_5,
NORDFORSK1_DV_B_6 = sp4_6,
NORDFORSK1_DV_B_7 = sp4_7,
NORDFORSK2_OBJECT = terror_2a,
NORDFORSK2_TENSE = terror_2b,
NORDFORSK2_DV = sp5,
NORDFORSK3 = sp6,
NORDFORSK4 = sp7,
NORDFORSK5 = sp8,
NORDFORSK6_1 = sp9_1,
NORDFORSK6_2 = sp9_2,
NORDFORSK6_3 = sp9_3,
NORDFORSK6_4 = sp9_4,
NORDFORSK6_5 = sp9_5,
NORDFORSK6_6 = sp9_6,
NORDFORSK7_EVENT = terror10_a,
NORDFORSK7_DV = sp10,
NORDFORSK8_PRE = sp12,
sp13, sp14,
NORDFORSK8_DV_B = sp15,
NORDFORSK8_DV_C = sp16,
GENDER = Gender,
AGE = Age,
EDUCATION = Education
) %>% 
  mutate(sp13 = as.character(sp13),
         sp14 = as.character(sp14),
         NORDFORSK5 = as_character(NORDFORSK5)
         )

di_pool <- di_pool %>% mutate(NORDFORSK1_TACTIC1 = case_when(NORDFORSK1_TACTIC1 == 'Protest' ~ 1,
                                                NORDFORSK1_TACTIC1 == 'Sabotage' ~ 2,
                                                NORDFORSK1_TACTIC1 == 'Hostage taking' ~ 3,
                                                NORDFORSK1_TACTIC1 == 'Shooting' ~ 4,
                                                NORDFORSK1_TACTIC1 == 'Bombing' ~ 5), 
                            NORDFORSK1_TARGET = case_when(NORDFORSK1_TARGET == 'military facility' ~ 1,
                                                           NORDFORSK1_TARGET == 'police station' ~ 2,
                                                           NORDFORSK1_TARGET == 'school' ~ 3,
                                                           NORDFORSK1_TARGET == 'church' ~ 4,
                                                           NORDFORSK1_TARGET == 'mosque' ~ 5,
                                                           NORDFORSK1_TARGET == 'synagogue' ~ 6),
                 NORDFORSK1_CASUALTIES = case_when(NORDFORSK1_CASUALTIES == 'No one was killed' ~ 1,
                                                   NORDFORSK1_CASUALTIES == 'One person' ~ 2,
                                                   NORDFORSK1_CASUALTIES == 'Two people' ~ 3,
                                                NORDFORSK1_CASUALTIES == 'Ten people' ~ 4),
                 NORDFORSK1_TACTIC2 = case_when(NORDFORSK1_TACTIC2 == 'Protest' ~ 1,
                                                NORDFORSK1_TACTIC2 == 'Sabotage' ~ 2,
                                                NORDFORSK1_TACTIC2 == 'Hostage taking' ~ 3,
                                                NORDFORSK1_TACTIC2 == 'Shooting' ~ 4,
                                                NORDFORSK1_TACTIC2 == 'Bombing' ~ 5),
                 NORDFORSK1_ADJECTIVE = case_when(NORDFORSK1_ADJECTIVE == 'one' ~ 1,
                                                NORDFORSK1_ADJECTIVE == 'one Christian' ~ 2,
                                                NORDFORSK1_ADJECTIVE == 'one Muslim' ~ 3,
                                                NORDFORSK1_ADJECTIVE == 'one left-wing extremist' ~ 4,
                                                NORDFORSK1_ADJECTIVE == 'one right-wing extremist' ~ 5),
                 NORDFORSK1_SUBJECTIVE = case_when(NORDFORSK1_SUBJECTIVE == 'organization' ~ 1,
                                                NORDFORSK1_SUBJECTIVE == 'group' ~ 2,
                                                NORDFORSK1_SUBJECTIVE == 'indiviudal' ~ 3,
                                                NORDFORSK1_SUBJECTIVE == 'individual of unsound mind' ~ 4),
                 NORDFORSK1_MOTIVATION = case_when(NORDFORSK1_MOTIVATION == 'there was no clear motivation behind the incident' ~ 1,
                                                NORDFORSK1_MOTIVATION == 'the incident was carried out with the aim of changing goverment policy' ~ 2,
                 NORDFORSK1_MOTIVATION == 'the motivation behind the incident came from a hatred towards the target' ~ 3),
                 NORDFORSK2_OBJECT = case_when(NORDFORSK2_OBJECT == 'for you personally' ~ 1,
                                               NORDFORSK2_OBJECT == 'Iceland' ~ 2,
                                               NORDFORSK2_OBJECT == 'Europe' ~ 3),
                 NORDFORSK2_TENSE = case_when(NORDFORSK2_TENSE == 'today' ~ 1,
                                              NORDFORSK2_TENSE == 'in the future' ~ 2),
                 NORDFORSK7_EVENT = case_when(  NORDFORSK7_EVENT == 'natural disasters' ~ 1,
                                                NORDFORSK7_EVENT == 'terrorist attack' ~ 2)

                 )

di_pool <- di_pool %>% mutate(AGE=replace(AGE, which(AGE <30), 1), # Reduce age categories in Icelandic data set to six
                              AGE=replace(AGE, which(AGE >=30 & AGE < 40), 2),
                              AGE=replace(AGE, which(AGE >=40 & AGE < 50), 3),
                              AGE=replace(AGE, which(AGE >=50 & AGE < 60), 4),
                              AGE=replace(AGE, which(AGE >=60 & AGE < 70), 5),
                              AGE=replace(AGE, which(AGE >=70), 6),
                              EDUCATION=replace(EDUCATION, which(EDUCATION <5), 0), # Reduce education categories in Icelandic data set to two
                              EDUCATION=replace(EDUCATION, which(EDUCATION >4 & EDUCATION <9), 1),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==2), 'Progress Party (Iceland)'), # Set new, unique values to prepare for pooling data sets
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==3), 'Reform Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==4), 'Independence Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==6), 'The Peoples Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==8), 'The Pirate Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==10), 'Social Democrats (Iceland)'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==11), 'Left-Green Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==12), 'The Center Party (Iceland)'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==13), 'Other'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==14), 'None'))

## Standardize sp13 and sp14 variables to harmonized format, separating the random assignment of treatment from post measure response
di_pool <- pivot_longer(di_pool, sp13:sp14, names_to = 'NORDFORSK8_TREAT', values_to = 'NORDFORSK8_DV_A', values_drop_na = TRUE) %>% 
   mutate(NORDFORSK8_TREAT=replace(NORDFORSK8_TREAT, which(NORDFORSK8_TREAT=='sp13'), '1'),
         NORDFORSK8_TREAT=replace(NORDFORSK8_TREAT, which(NORDFORSK8_TREAT=='sp14'), '0'),
         )
```

```{r pool_load_norway}

#Norway
## Load data
dn <- read_sav('C:\\Users/svein/Documents/nordforskdata/Norwegian Citizen Panel - wave 15 - EN.sav')
dn <- dn %>% select(starts_with('r15pad_terror'), responseid, r15P1, r15P4_2, r15P5_1) %>% filter(!is.na(r15pad_terror1_ran1))

## Select variables and rename to harmonized variable names
dn_pool <- dn %>% select(ResponseId = responseid,
NORDFORSK1_TACTIC1 = r15pad_terror1_ran1,
NORDFORSK1_TARGET = r15pad_terror1_ran3,
NORDFORSK1_CASUALTIES = r15pad_terror1_ran4,
NORDFORSK1_TACTIC2 = r15pad_terror1_ran5,
NORDFORSK1_ADJECTIVE = r15pad_terror1_ran6,
NORDFORSK1_SUBJECTIVE = r15pad_terror1_ran7,
NORDFORSK1_MOTIVATION = r15pad_terror1_ran8,
NORDFORSK1_DV_A = r15pad_terror1_a,
NORDFORSK1_DV_B_1 = r15pad_terror1_b_1,
NORDFORSK1_DV_B_2 = r15pad_terror1_b_2,
NORDFORSK1_DV_B_3 = r15pad_terror1_b_3,
NORDFORSK1_DV_B_4 = r15pad_terror1_b_4,
NORDFORSK1_DV_B_5 = r15pad_terror1_b_5,
NORDFORSK1_DV_B_6 = r15pad_terror1_b_6,
NORDFORSK1_DV_B_7 = r15pad_terror1_b_7,
NORDFORSK2_OBJECT = r15pad_terror2_ran1,
NORDFORSK2_TENSE = r15pad_terror2_ran2,
NORDFORSK2_DV = r15pad_terror2,
NORDFORSK3 = r15pad_terror3,
NORDFORSK4 = r15pad_terror5,
NORDFORSK5 = r15pad_terror6,
NORDFORSK6_1 = r15pad_terror8_1,
NORDFORSK6_2 = r15pad_terror8_2,
NORDFORSK6_3 = r15pad_terror8_3,
NORDFORSK6_4 = r15pad_terror8_4,
NORDFORSK6_5 = r15pad_terror8_5,
NORDFORSK6_6 = r15pad_terror8_6,
NORDFORSK7_EVENT = r15pad_terror10_ran,
NORDFORSK7_DV = r15pad_terror10,
NORDFORSK8_PRE = r15pad_terror11pre,
NORDFORSK8_TREAT = r15pad_terror11_ran, 
NORDFORSK8_DV_A =  r15pad_terror11posta,
NORDFORSK8_DV_B =  r15pad_terror11postb,
NORDFORSK8_DV_C = r15pad_terror11postc,
GENDER = r15P1,
AGE = r15P5_1,
EDUCATION = r15P4_2) %>% 
  mutate(ResponseId = as.character(ResponseId), #standardise object class among the data sets
          ) 

##Standardize values to pooled data set
dn_pool <- dn_pool %>% mutate(NORDFORSK1_DV_A=replace(NORDFORSK1_DV_A, which(NORDFORSK1_DV_A>96), NA), # Convert 97 values to NA to conform to pooled standard
                              NORDFORSK1_DV_B_1=replace(NORDFORSK1_DV_B_1, which(NORDFORSK1_DV_B_1>96), NA),
                              NORDFORSK1_DV_B_2=replace(NORDFORSK1_DV_B_2, which(NORDFORSK1_DV_B_2>96), NA),
                              NORDFORSK1_DV_B_3=replace(NORDFORSK1_DV_B_3, which(NORDFORSK1_DV_B_3>96), NA),
                              NORDFORSK1_DV_B_4=replace(NORDFORSK1_DV_B_4, which(NORDFORSK1_DV_B_4>96), NA),
                              NORDFORSK1_DV_B_5=replace(NORDFORSK1_DV_B_5, which(NORDFORSK1_DV_B_5>96), NA),
                              NORDFORSK1_DV_B_6=replace(NORDFORSK1_DV_B_6, which(NORDFORSK1_DV_B_6>96), NA),
                              NORDFORSK1_DV_B_7=replace(NORDFORSK1_DV_B_7, which(NORDFORSK1_DV_B_7>96), NA),
                              NORDFORSK2_DV=replace(NORDFORSK2_DV, which(NORDFORSK2_DV>96), NA),
                              NORDFORSK3=replace(NORDFORSK3, which(NORDFORSK3>96), NA),
                              NORDFORSK4=replace(NORDFORSK4, which(NORDFORSK4>96), NA),
                              NORDFORSK6_1=replace(NORDFORSK6_1, which(NORDFORSK6_1>96), NA),
                              NORDFORSK6_2=replace(NORDFORSK6_2, which(NORDFORSK6_2>96), NA),
                              NORDFORSK6_3=replace(NORDFORSK6_3, which(NORDFORSK6_3>96), NA),
                              NORDFORSK6_4=replace(NORDFORSK6_4, which(NORDFORSK6_4>96), NA),
                              NORDFORSK6_5=replace(NORDFORSK6_5, which(NORDFORSK6_5>96), NA),
                              NORDFORSK6_6=replace(NORDFORSK6_6, which(NORDFORSK6_6>96), NA),
                              NORDFORSK7_DV=replace(NORDFORSK7_DV, which(NORDFORSK7_DV>96), NA),
                              NORDFORSK8_PRE=replace(NORDFORSK8_PRE, which(NORDFORSK8_PRE>96), NA),
                              NORDFORSK8_DV_A=replace(NORDFORSK8_DV_A, which(NORDFORSK8_DV_A>96), NA),
                              NORDFORSK8_DV_B=replace(NORDFORSK8_DV_B, which(NORDFORSK8_DV_B>96), NA),
                              NORDFORSK8_DV_C=replace(NORDFORSK8_DV_C, which(NORDFORSK8_DV_C>96), NA),
                              AGE=replace(AGE, which(AGE >5), 1), # Reduce age categories in Norwegian data set to six and revert scale to fit other data sets
                              AGE=replace(AGE, which(AGE ==5), 2),
                              AGE=replace(AGE, which(AGE ==4), 3),
                              AGE=replace(AGE, which(AGE ==3), 4),
                              AGE=replace(AGE, which(AGE ==2), 5),
                              AGE=replace(AGE, which(AGE ==1), 6),
                              EDUCATION=replace(EDUCATION, which(EDUCATION <6), 0), # Reduce education categories in Norwegian data set to two
                              EDUCATION=replace(EDUCATION, which(EDUCATION >5 & EDUCATION <12), 1),
                              EDUCATION=replace(EDUCATION, which(EDUCATION >11), NA),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='1'), 'The Labour Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='2'), 'The Progress Party (Norway)'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='3'), 'The Conservative Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='4'), 'The Socialist Left Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='5'), 'The Centre Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='6'), 'The Christian Democrats (Norway)'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='7'), 'The Liberal Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='8'), 'The Red Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='9'), 'The Green Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='10'), 'Other'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='11'), 'None'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5=='97'), NA)
                              #,
                              #NORDFORSK5 = as_character(NORDFORSK5)
                                                )
```

```{r pool_load_sweden}
#Sweden
## Load data
ds <- read_dta('C:\\Users/svein/Documents/nordforskdata/s5_sohlberg.dta') 

## Select variables and rename to harmonized variable names
ds_pool <- ds %>% select(c(#ResponseId = responseid,
NORDFORSK1_TACTIC1 = q269_incidenttyp,
NORDFORSK1_TARGET = q269_plats,
NORDFORSK1_CASUALTIES = q269_omkomna,
NORDFORSK1_TACTIC2 = q269_incidenten,
NORDFORSK1_ADJECTIVE = q269_ideologi,
NORDFORSK1_SUBJECTIVE = q269_subjekt,
NORDFORSK1_MOTIVATION = q269_motiv,
NORDFORSK1_DV_A = q270,
NORDFORSK1_DV_B_1 = q272_1,
NORDFORSK1_DV_B_2 = q272_2,
NORDFORSK1_DV_B_3 = q272_3,
NORDFORSK1_DV_B_4 = q272_4,
NORDFORSK1_DV_B_5 = q272_5,
NORDFORSK1_DV_B_6 = q272_6,
NORDFORSK1_DV_B_7 = q272_7,
NORDFORSK2_OBJECT = q274_hot,
NORDFORSK2_TENSE = q274_tempus,
NORDFORSK2_DV = q274,
NORDFORSK3 = q276,
NORDFORSK4 = q278,
NORDFORSK5 = q280,
NORDFORSK6_1 = q282_1,
NORDFORSK6_2 = q282_2,
NORDFORSK6_3 = q282_3,
NORDFORSK6_4 = q282_4,
NORDFORSK6_5 = q282_5,
NORDFORSK6_6 = q282_6,
NORDFORSK7_EVENT = q284_kristyp,
NORDFORSK7_DV = q284,
NORDFORSK8_PRE = q286,
NORDFORSK8_TREAT = q288,
NORDFORSK8_DV_A =  q290,
NORDFORSK8_DV_B =  q292,
NORDFORSK8_DV_C = q294,
GENDER = sex,
AGE = age6,
EDUCATION = edu_mp36)
) %>% 
  mutate(NORDFORSK8_TREAT = as_numeric(NORDFORSK8_TREAT),
        NORDFORSK5 = as_numeric(NORDFORSK5)
         )

ds_pool <- ds_pool %>% mutate(NORDFORSK1_TACTIC1 = case_when(NORDFORSK1_TACTIC1 == 'En protest' ~ 1,
                                                NORDFORSK1_TACTIC1 == 'Ett sabotage' ~ 2,
                                                NORDFORSK1_TACTIC1 == 'Ett gisslantagande' ~ 3,
                                                NORDFORSK1_TACTIC1 == 'En skjutning' ~ 4,
                                                NORDFORSK1_TACTIC1 == 'En bombning' ~ 5), 
                            NORDFORSK1_TARGET = case_when(NORDFORSK1_TARGET == 'på en militäranläggning' ~ 1,
                                                          NORDFORSK1_TARGET == 'på en polisstation' ~ 2,
                                                          NORDFORSK1_TARGET == 'i en skola' ~ 3,
                                                          NORDFORSK1_TARGET == 'i en kyrka' ~ 4,
                                                          NORDFORSK1_TARGET == 'i en moské' ~ 5,
                                                          NORDFORSK1_TARGET == 'i en synagoga' ~ 6),
                 NORDFORSK1_CASUALTIES = case_when(NORDFORSK1_CASUALTIES == 'Ingen' ~ 1,
                                                   NORDFORSK1_CASUALTIES == 'En person' ~ 2,
                                                NORDFORSK1_CASUALTIES == 'Två personer' ~ 3,
                                                NORDFORSK1_CASUALTIES == 'Tio personer' ~ 4),
                 NORDFORSK1_TACTIC2 = case_when(NORDFORSK1_TACTIC2 == 'protesten' ~ 1,
                                                NORDFORSK1_TACTIC2 == 'sabotaget' ~ 2,
                                                NORDFORSK1_TACTIC2 == 'gisslantagningen' ~ 3,
                                                NORDFORSK1_TACTIC2 == 'skjutningen' ~ 4,
                                                NORDFORSK1_TACTIC2 == 'bombningen' ~ 5),
                 NORDFORSK1_ADJECTIVE = case_when(NORDFORSK1_ADJECTIVE == 'en' ~ 1,
                                                NORDFORSK1_ADJECTIVE == 'en kristen' ~ 2,
                                                NORDFORSK1_ADJECTIVE == 'en muslimsk' ~ 3,
                                                NORDFORSK1_ADJECTIVE == 'en vänsterextrem' ~ 4,
                                                NORDFORSK1_ADJECTIVE == 'en högerextrem' ~ 5),
                 NORDFORSK1_SUBJECTIVE = case_when(NORDFORSK1_SUBJECTIVE == 'organiSation' ~ 1,
                                                NORDFORSK1_SUBJECTIVE == 'grupp' ~ 2,
                                                NORDFORSK1_SUBJECTIVE == 'individ' ~ 3,
                                                NORDFORSK1_SUBJECTIVE == 'psykiskt sjuk individ' ~ 4),
                 NORDFORSK1_MOTIVATION = case_when(NORDFORSK1_MOTIVATION == 'att det inte fanns något tydligt motiv bakom händelsen' ~ 1,
                                                NORDFORSK1_MOTIVATION == 'att händelsen utfördes med målet att förändra regeringens politik' ~ 2,
                 NORDFORSK1_MOTIVATION == 'att händelsen var motiverad utifrån hat gentemot målet' ~ 3),
                 NORDFORSK2_OBJECT = case_when(NORDFORSK2_OBJECT == 'dig personligen' ~ 1,
                                               NORDFORSK2_OBJECT == 'Sverige' ~ 2,
                                               NORDFORSK2_OBJECT == 'Europa' ~ 3),
                 NORDFORSK2_TENSE = case_when(NORDFORSK2_TENSE == 'idag' ~ 1,
                                              NORDFORSK2_TENSE == 'i framtiden' ~ 2),
                 NORDFORSK7_EVENT = case_when(NORDFORSK7_EVENT == 'naturkatastrofer' ~ 1,
                                                NORDFORSK7_EVENT == 'terrorattacker' ~ 2)

                 )

ds_pool <- ds_pool %>% mutate(EDUCATION=replace(EDUCATION, which(EDUCATION <7), 0), # Reduce education categories in Swedish data set to two
                              EDUCATION=replace(EDUCATION, which(EDUCATION >6 & EDUCATION <10), 1),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==1), 'The Social Democrats'), #Give Swedish political parties unique values
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==2), 'The Sweden Democrats'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==3), 'The Moderates'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==4), 'The Left Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==5), 'The Centre Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==6), 'The Christian Democrats (Sweden)'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==7), 'The Liberal Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==8), 'The Green Party'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==9), 'Other'),
                              NORDFORSK5= replace(NORDFORSK5, which(NORDFORSK5==10), 'None')) %>% 
 set_labels(NORDFORSK5, labels = c('The Social Democrats' = 'The Social Democrats', # Swedish political parties
                             'The Sweden Democrats' = 'The Sweden Democrats',
                             'The Moderates' = 'The Moderates',
                             'The Left Party' = 'The Left Party',
                             'The Centre Party' = 'The Centre Party',
                             'The Christian Democrats (Sweden)' = 'The Christian Democrats (Sweden)',
                             'The Liberal Party' = 'The Liberal Party',
                             'The Green Party' = 'The Green Party',
                             'Other' = 'Other',
                             'None' = 'None'
                             ))
                                    
                                                                              
```

```{r pool_bind}
#Merge data sets from Iceland, Norway, and Sweden
d_pool <- bind_rows(di_pool, dn_pool, ds_pool)
```
```{r pool_eng_values}
# Standardise values across data sets
# d_pool <- d_pool %>% mutate(NORDFORSK1_TACTIC1 = case_when(NORDFORSK1_TACTIC1 == 'Protest' ~ 1,
#                                                            NORDFORSK1_TACTIC1 == 'En protest' ~ 1,
#                                                 NORDFORSK1_TACTIC1 == 'Sabotage' ~ 2,
#                                                 NORDFORSK1_TACTIC1 == 'Ett sabotage' ~ 2,
#                                                 NORDFORSK1_TACTIC1 == 'Hostage taking' ~ 3,
#                                                 NORDFORSK1_TACTIC1 == 'Ett gisslantagande' ~ 3,
#                                                 NORDFORSK1_TACTIC1 == 'Shooting' ~ 4,
#                                                 NORDFORSK1_TACTIC1 == 'En skjutning' ~ 4,
#                                                 NORDFORSK1_TACTIC1 == 'Bombing' ~ 5,
#                                                 NORDFORSK1_TACTIC1 == 'En bombning' ~ 5), 
#                             NORDFORSK1_TARGET = case_when(NORDFORSK1_TARGET == 'military facility' ~ 1,
#                                                           NORDFORSK1_TARGET == 'på en militäranläggning' ~ 1,
#                                                            NORDFORSK1_TARGET == 'police station' ~ 2,
#                                                           NORDFORSK1_TARGET == 'på en polisstation' ~ 2,
#                                                            NORDFORSK1_TARGET == 'school' ~ 3,
#                                                           NORDFORSK1_TARGET == 'i en skola' ~ 3,
#                                                            NORDFORSK1_TARGET == 'church' ~ 4,
#                                                           NORDFORSK1_TARGET == 'i en kyrka' ~ 4,
#                                                            NORDFORSK1_TARGET == 'mosque' ~ 5,
#                                                           NORDFORSK1_TARGET == 'i en moské' ~ 5,
#                                                            NORDFORSK1_TARGET == 'synagogue' ~ 6,
#                                                           NORDFORSK1_TARGET == 'i en synagoga' ~ 6),
#                  NORDFORSK1_CASUALTIES = case_when(NORDFORSK1_CASUALTIES == 'No one was killed' ~ 1,
#                                                    NORDFORSK1_CASUALTIES == 'Ingen' ~ 1,
#                                                    NORDFORSK1_CASUALTIES == 'One person' ~ 2,
#                                                    NORDFORSK1_CASUALTIES == 'En person' ~ 2,
#                                                    NORDFORSK1_CASUALTIES == 'Two people' ~ 3,
#                                                 NORDFORSK1_CASUALTIES == 'Två personer' ~ 3,
#                                                 NORDFORSK1_CASUALTIES == 'Ten people' ~ 4,
#                                                 NORDFORSK1_CASUALTIES == 'Tio personer' ~ 4),
#                  NORDFORSK1_TACTIC2 = case_when(NORDFORSK1_TACTIC2 == 'Protest' ~ 1,
#                                                 NORDFORSK1_TACTIC2 == 'protesten' ~ 1,
#                                                 NORDFORSK1_TACTIC2 == 'Sabotage' ~ 2,
#                                                 NORDFORSK1_TACTIC2 == 'sabotaget' ~ 2,
#                                                 NORDFORSK1_TACTIC2 == 'Hostage taking' ~ 3,
#                                                 NORDFORSK1_TACTIC2 == 'gisslantagningen' ~ 3,
#                                                 NORDFORSK1_TACTIC2 == 'Shooting' ~ 4,
#                                                 NORDFORSK1_TACTIC2 == 'skjutningen' ~ 4,
#                                                 NORDFORSK1_TACTIC2 == 'Bombing' ~ 5,
#                                                 NORDFORSK1_TACTIC2 == 'bombningen' ~ 5),
#                  NORDFORSK1_ADJECTIVE = case_when(NORDFORSK1_ADJECTIVE == 'one' ~ 1,
#                                                   NORDFORSK1_ADJECTIVE == 'en' ~ 1,
#                                                 NORDFORSK1_ADJECTIVE == 'one Christian' ~ 2,
#                                                 NORDFORSK1_ADJECTIVE == 'en kristen' ~ 2,
#                                                 NORDFORSK1_ADJECTIVE == 'one Muslim' ~ 3,
#                                                 NORDFORSK1_ADJECTIVE == 'en muslimsk' ~ 3,
#                                                 NORDFORSK1_ADJECTIVE == 'one left-wing extremist' ~ 4,
#                                                 NORDFORSK1_ADJECTIVE == 'en vänsterextrem' ~ 4,
#                                                 NORDFORSK1_ADJECTIVE == 'one right-wing extremist' ~ 5,
#                                                 NORDFORSK1_ADJECTIVE == 'en högerextrem' ~ 5),
#                  NORDFORSK1_SUBJECTIVE = case_when(NORDFORSK1_SUBJECTIVE == 'organization' ~ 1,
#                                                    NORDFORSK1_SUBJECTIVE == 'organiSation' ~ 1,
#                                                 NORDFORSK1_SUBJECTIVE == 'group' ~ 2,
#                                                 NORDFORSK1_SUBJECTIVE == 'grupp' ~ 2,
#                                                 NORDFORSK1_SUBJECTIVE == 'indiviudal' ~ 3,
#                                                 NORDFORSK1_SUBJECTIVE == 'individ' ~ 3,
#                                                 NORDFORSK1_SUBJECTIVE == 'individual of unsound mind' ~ 4,
#                                                 NORDFORSK1_SUBJECTIVE == 'psykiskt sjuk individ' ~ 4),
#                  NORDFORSK1_MOTIVATION = case_when(NORDFORSK1_MOTIVATION == 'there was no clear motivation behind the incident' ~ 1,
#                                                    NORDFORSK1_MOTIVATION == 'att det inte fanns något tydligt motiv bakom händelsen' ~ 1,
#                                                 NORDFORSK1_MOTIVATION == 'the incident was carried out with the aim of changing goverment policy' ~ 2,
#                                                 NORDFORSK1_MOTIVATION == 'att händelsen utfördes med målet att förändra regeringens politik' ~ 2,
#                  NORDFORSK1_MOTIVATION == 'the motivation behind the incident came from a hatred towards the target' ~ 3,
#                  NORDFORSK1_MOTIVATION == 'att händelsen var motiverad utifrån hat gentemot målet' ~ 3),
#                  NORDFORSK2_OBJECT = case_when(NORDFORSK2_OBJECT == 'for you personally' ~ 1,
#                                                NORDFORSK2_OBJECT == 'dig personligen' ~ 1,
#                                                NORDFORSK2_OBJECT == 'Iceland' ~ 2,
#                                                NORDFORSK2_OBJECT == 'Sverige' ~ 2,
#                                                NORDFORSK2_OBJECT == 'Europe' ~ 3,
#                                                NORDFORSK2_OBJECT == 'Europa' ~ 3),
#                  NORDFORSK2_TENSE = case_when(NORDFORSK2_TENSE == 'today' ~ 1,
#                                               NORDFORSK2_TENSE == 'idag' ~ 1,
#                                               NORDFORSK2_TENSE == 'in the future' ~ 2,
#                                               NORDFORSK2_TENSE == 'i framtiden' ~ 2),
#                  NORDFORSK7_EVENT = case_when(  NORDFORSK7_EVENT == 'natural disasters' ~ 1,
#                                                 NORDFORSK7_EVENT == 'naturkatastrofer' ~ 1,
#                                                 NORDFORSK7_EVENT == 'terrorist attack' ~ 2,
#                                                 NORDFORSK7_EVENT == 'terrorattacker' ~ 2)
# 
#                  )
```

```{r set_labels}
# Set labels for the pooled data set
d_pool <- d_pool %>% set_labels(NORDFORSK1_TACTIC1, labels = c('protest' = 1,
                                                               'sabotage' = 2,
                                                               'hostage taking' = 3,
                                                               'shooting' = 4,
                                                               'bombing' =5)) %>% 
  set_labels(NORDFORSK1_TARGET, labels = c('a military facility' = 1,
                                                               'a police station' = 2,
                                                               'a school' = 3,
                                                               'a church' = 4,
                                                               'a mosque' = 5)) %>% 
  set_labels(NORDFORSK1_CASUALTIES, labels = c('No' = 1,
                                               'One person' = 2,
                                               'Two people' = 3,
                                               'Ten people' = 4)) %>% 
  set_labels(NORDFORSK1_TACTIC2, labels = c('the protest' = 1,
                                                               'the sabotage' = 2,
                                                               'the hostage taking' = 3,
                                                               'the shooting' = 4,
                                                               'the bombing' =5)) %>% 
  set_labels(NORDFORSK1_ADJECTIVE, labels = c('one' = 1,
                                              'one Christian' = 2,
                                              'one Muslim' = 3,
                                              'one left-wing extremist' = 4,
                                              'one right-wing extremist' = 5)) %>% 
  set_labels(NORDFORSK1_SUBJECTIVE, labels = c('organisation' = 1,
                                              'group' = 2,
                                              'individual' = 3,
                                              'individual of unsound mind' = 4)) %>% 
    set_labels(NORDFORSK1_MOTIVATION, labels = c('there was no clear motivation behind the incident' = 1,
                                              'the incident was carried out with the aim of changing government policy' = 2,
                                              'the motivation behind the incident came from a hatred towards the target' = 3)) %>% 
set_labels(NORDFORSK1_DV_A, labels = c('Yes, this is terrorism' = 1,
                                                              'No, this is not terrorism' = 2)) %>% 
  set_labels(NORDFORSK1_DV_B_1, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK1_DV_B_2, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK1_DV_B_3, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK1_DV_B_4, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK1_DV_B_5, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK1_DV_B_6, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK1_DV_B_7, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK2_OBJECT, labels = c('you personally' = 1,
                                           '[country]' = 2,
                                           'Europe' = 3)) %>% 
  set_labels(NORDFORSK2_TENSE, labels = c('today' = 1,
                                          'in the future' = 2)) %>% 
  set_labels(NORDFORSK2_DV, labels = c('Very serious' = 1,
                                                              'Serious' = 2,
                                                              'Somewhat serious' = 3,
                                                              'Not very serious' = 4,
                                                              'Not a threat' = 5)) %>% 
  set_labels(NORDFORSK3, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(NORDFORSK4, labels = c('Very important' = 1,
                                                              'Important' = 2,
                                                              'Somewhat important' = 3,
                                                              'Slightly important' = 4,
                                                              'Not important at all' = 5)) %>% 
 set_labels(NORDFORSK6_1, labels = c('Extremely good' = 1,
                                                              'Very good' = 2,
                                                              'Somewhat good' = 3,
                                                              'Neither good nor bad' = 4,
                                                              'Somewhat bad' = 5,
                                                              'Very bad' = 6,
                                                              'Extremely bad' = 7)) %>% 
  set_labels(NORDFORSK6_2, labels = c('Extremely good' = 1,
                                                              'Very good' = 2,
                                                              'Somewhat good' = 3,
                                                              'Neither good nor bad' = 4,
                                                              'Somewhat bad' = 5,
                                                              'Very bad' = 6,
                                                              'Extremely bad' = 7)) %>% 
  set_labels(NORDFORSK6_3, labels = c('Extremely good' = 1,
                                                              'Very good' = 2,
                                                              'Somewhat good' = 3,
                                                              'Neither good nor bad' = 4,
                                                              'Somewhat bad' = 5,
                                                              'Very bad' = 6,
                                                              'Extremely bad' = 7)) %>% 
  set_labels(NORDFORSK6_4, labels = c('Extremely good' = 1,
                                                              'Very good' = 2,
                                                              'Somewhat good' = 3,
                                                              'Neither good nor bad' = 4,
                                                              'Somewhat bad' = 5,
                                                              'Very bad' = 6,
                                                              'Extremely bad' = 7)) %>% 
  set_labels(NORDFORSK6_5, labels = c('Extremely good' = 1,
                                                              'Very good' = 2,
                                                              'Somewhat good' = 3,
                                                              'Neither good nor bad' = 4,
                                                              'Somewhat bad' = 5,
                                                              'Very bad' = 6,
                                                              'Extremely bad' = 7)) %>% 
  set_labels(NORDFORSK6_6, labels = c('Extremely good' = 1,
                                                              'Very good' = 2,
                                                              'Somewhat good' = 3,
                                                              'Neither good nor bad' = 4,
                                                              'Somewhat bad' = 5,
                                                              'Very bad' = 6,
                                                              'Extremely bad' = 7)) %>% 
  set_labels(NORDFORSK7_EVENT, labels = c('natural disasters' = 1,
                                          'terrorist attack' = 2)) %>% 
    set_labels(NORDFORSK7_DV, labels = c('I support it very strongly' = 1,
                                                              'I support it strongly' = 2,
                                                              'I support it somewhat' = 3,
                                                              'I neither support it nor oppose it' = 4,
                                                              'I oppose it somewhat' = 5,
                                                              'I oppose it strongly' = 6,
                                                              'I oppose it very strongly' = 7)) %>% 
    set_labels(NORDFORSK8_PRE, labels = c('It led to a lot more terrorism' = 1,
                                                              'It led to somewhat more terrorism' = 2,
                                                              'It did not lead to any more or any less terrorism' = 3,
                                                              'It led to less terrorism' = 4,
                                                              'It led to a lot less terrorism' = 5)) %>% 
  set_labels(NORDFORSK8_DV_A, labels = c('Increase greatly' = 1,
                                                              'Increase' = 2,
                                                              'Increase somewhat' = 3,
                                                              'Neither increase nor decrease' = 4,
                                                              'Decrease somewhat' = 5,
                                                              'Decrease' = 6,
                                                              'Decrease greatly' = 7)) %>% 
  set_labels(NORDFORSK8_DV_B, labels = c('Receive many more' = 1,
                                                              'Receive more' = 2,
                                                              'Receive a few more' = 3,
                                                              'Neither receive any more nor any less' = 4,
                                                              'Receive a few less' = 5,
                                                              'Receive fewer' = 6,
                                                              'Receive many fewer' = 7))  %>% 
  set_labels(NORDFORSK8_DV_C, labels = c('Strongly agree' = 1,
                                                              'Agree' = 2,
                                                              'Agree somewhat' = 3,
                                                              'Neither agree nor disagree' = 4,
                                                              'Disagree somewhat' = 5,
                                                              'Disagree' = 6,
                                                              'Strongly disagree' = 7)) %>% 
  set_labels(AGE, labels = c('Under 30' = 1,
                             '30-39' = 2,
                             '40-49' = 3,
                             '50-59' = 4,
                             '60-69' = 5,
                             '70 or older' = 6))

  
  
  
  
ds_pool %>% surveytoolbox::extract_vallab('NORDFORSK5')

```


