# NORDFORSK4

```{r nordforsk4_setup, include=FALSE, echo=FALSE}
if(!require("gt")){install.packages("gt");  library(gt)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
if(!require("magick")){install.packages("magick");  library(magick)}
if(!require("openxlsx")){install.packages("openxlsx");  library(openxlsx)}
if(!require("readxl")){install.packages("readxl");  library(readxl)}
if(!require("sjlabelled")){install.packages("sjlabelled");  library(sjlabelled)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}
if(!require("utf8")){install.packages("utf8");  library(utf8)}
if(!require("webshot")){install.packages("webshot");  library(webshot)}

knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = "", cache = FALSE, message = FALSE )
```

> How important are anti-terrorism measures for you personally?

*Translations*

Iceland

Hversu mikilvægar finnst þér aðgerðir gegn hryðjuverkum vera?

Norway  
Hvor viktig er antiterrortiltak for deg.

Sweden 
Hur viktiga är åtgärder mot terrorism för dig personligen?

```{r nordforsk4}
Source = c('Very important', 'Important', 'Somewhat important', 'Slightly important', 'Not important at all', NA)
Iceland <- count(di, sp7)  
Norway <- count(dn, as_label(r15pad_terror5)) %>% filter(`as_label(r15pad_terror5)` != 'Ikke spurt')
Sweden <- count(ds, q278) %>% filter(n > 10)
nordforsk3 <- bind_cols(Source, Iceland, Norway, Sweden)

kable(nordforsk3, booktabs = T, linesep = "", escape = F, caption = "Panel variable names and values",  col.names = linebreak(c("Source Questionnaire", "Iceland", 'n', "Norway", 'n', "Sweden", 'n'))) %>%
  footnote(general = "Variable names. Iceland = sp7, Norway =  r15pad_terror5, Sweden = q278")
```
