# NORDFORSK5

```{r nordforsk5_setup, include=FALSE, echo=FALSE}
if(!require("gt")){install.packages("gt");  library(gt)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
if(!require("magick")){install.packages("magick");  library(magick)}
if(!require("openxlsx")){install.packages("openxlsx");  library(openxlsx)}
if(!require("readxl")){install.packages("readxl");  library(readxl)}
if(!require("sjlabelled")){install.packages("sjlabelled");  library(sjlabelled)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}
if(!require("utf8")){install.packages("utf8");  library(utf8)}
if(!require("webshot")){install.packages("webshot");  library(webshot)}

knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = "", cache = FALSE, message = FALSE )
```

> Which political party do you think has the best policies aimed at combating terrorist attacks in [Iceland / Norway / Sweden]?

*Translations*

Iceland  
Hvaða stjórnmálaflokkur telur þú að hafi bestu stefnu til að sporna við hryðjuverkum á Íslandi?

Norway  
Hvilket parti har den beste antiterrorpolitikken.

Sweden  
Bästa part för bekämpa terrorism?

```{r nordforsk5}
Source <- rep(NA, each = 12)
Iceland <- count(di, as_label(sp8)) %>% add_row(`as_label(sp8)` = NA, n = NA)
Norway <- count(dn, as_label(r15pad_terror6)) %>% filter(`as_label(r15pad_terror6)` != 'Ikke spurt')
Sweden <- count(ds, as_label(q280)) %>% add_row(`as_label(q280)`= NA, n = NA)
nordforsk5 <- bind_cols(Source, Iceland, Norway, Sweden)

kable(nordforsk5, booktabs = T, linesep = "", escape = F, caption = "Panel variable names and values",  col.names = linebreak(c("Source Questionnaire", "Iceland", 'n', "Norway", 'n', "Sweden", 'n'))) %>%
  footnote(general = "Variable names. Iceland = sp8, Norway =  r15pad_terror6, Sweden = q280")
```
