# GENDER


```{r GENDER_setup, include=FALSE, echo=FALSE}
if(!require("gt")){install.packages("gt");  library(gt)}
if(!require("haven")){install.packages("haven");  library(haven)}
if(!require("here")){install.packages("here");  library(here)}
if(!require("kableExtra")){install.packages("kableExtra");  library(kableExtra)}
if(!require("knitr")){install.packages("knitr");  library(knitr)}
if(!require("magick")){install.packages("magick");  library(magick)}
if(!require("openxlsx")){install.packages("openxlsx");  library(openxlsx)}
if(!require("readxl")){install.packages("readxl");  library(readxl)}
if(!require("sjlabelled")){install.packages("sjlabelled");  library(sjlabelled)}
if(!require("tidyverse")){install.packages("tidyverse");  library(tidyverse)}
if(!require("utf8")){install.packages("utf8");  library(utf8)}
if(!require("webshot")){install.packages("webshot");  library(webshot)}

knitr::opts_chunk$set(echo = FALSE, knitr.kable.NA = "", cache = FALSE, message = FALSE )
```


```{r GENDER_PRE}
Source <- c('Male', 'Female')
Iceland <- count(di_is, as_label(kyn))
Norway <- count(dn, as_label(r15P1))
Sweden <- count(ds, as_label(sex)) 
GENDER <- bind_cols(Source, Iceland, Norway, Sweden)

kable(GENDER, booktabs = T, linesep = "", escape = F, caption = "Panel variable names and values",  col.names = linebreak(c("Source Questionnaire", "Iceland", 'n', "Norway", 'n', "Sweden", 'n'))) %>%
  footnote(general = "Variable names. Iceland = kyn, Norway =  r15P1, Sweden = sex")
```
